### ISSUE TITLE
WP6.4  Cryosphere

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2pilot#6]
- [ ] Design and develop WIS2 node
- [ ] Define datasets and topics
- [ ] Define Center identifier
- [ ] Implement software for the WIS2 node
- [ ] Register WIS2 node 
- [ ] Develop metadata
- [ ] Publish notifications through the GBs
- [ ] Provide access to GBs and GCs
- [ ] Start WIS2 data sharing through the Global Services
